//
//  Flooring.swift
//
//  Created by Aries Aviles on 9/23/21.
//

import SwiftUI

struct Flooring: Identifiable {
    var id: Int
    var name: String
    var colorName: String
    var flooringType: String
    var description: String
    var productSpecs: [String] // even: spec types, odd: descriptors
    var imageURLs: [String] // array contianing multiple images, first is texture
    var ahap: String
    var collision: String
}

let MOCK_FLOORING: [Flooring] = [
    .init(id: 0, name: "Subtle Aura", colorName: "Candle Light", flooringType: "Carpet", description: "Refined + effortless, the Caress Collection is styled for you. Featuring Anso® Nylon with R2X® built-in stain & soil protection, LifeGuard® Spill-Proof Backing™ and a 20-year warranty, Caress offers the best in style and design.", productSpecs: ["Flooring Type", "Carpet", "Fiber", "100% ANSO® NYLON", "Backing", "Lifeguard Blue", "Country of Origin", "US"], imageURLs: ["subtleaura-crop"], ahap: "Texture", collision: "CollisionLarge"),
    .init(id: 1, name: "Expressions", colorName: "Prose", flooringType: "Wood", description: "Warm up rooms and reduce energy bills with the natural insulation and comfort of carpet. With many styles to choose from and the best stain-fighting technology in the industry, Shaw carpet brings color, texture and value to your floors. Create distinctively stylish looks when you play with texture, loop, pattern and twist options.", productSpecs: ["Flooring Type", "Carpet", "Fiber", "100% Anso Soft BCF Nylon", "Backing", "Softbac Platinum", "Country of Origin", "US"], imageURLs: ["expressions-crop"], ahap: "Texture-solid", collision: "CollisionSmall"),
    
    .init(id: 2, name: "Arden", colorName: "Weathered", flooringType: "Hardwood", description: "Arden Oak 3 1/4 is a classic oak hardwood floor that showcases the charm, character and natural beauty of hardwood.", productSpecs: ["Flooring Type", "Hardwood", "Species", "Red Oak", "Plank Width", "3.25", "Edge Profile", "Micro Bevel", "Surface Texture", "Smooth"],  imageURLs: ["revivalmaria-crop"], ahap: "Texture-solid", collision: "CollisionSmall"),
    
    .init(id: 3, name: "Revival Isabella", colorName: "Agate", flooringType: "Stone/Tile", description: "Our stunning tile & stone collections allow you to unleash your creativity with endless combinations. Designed to mimic the natural textures, like quarried slate, travertine and limestone, these looks embody flooring sophistication. Shaw tile & stone is available in ceramic, porcelain and stone and includes eco-friendly options to meet your various project needs.", productSpecs: ["Flooring Type", "TileStone", "Surface Texture", "Encaustic", "Surface Finish", "Matte", "Frost Resistant", "Yes"], imageURLs: ["galleria-crop"], ahap: "Texture-solid", collision: "CollisionSmall")

]

let CARPET_FLOORING: [Flooring] = [
    .init(id: 0, name: "Subtle Aura", colorName: "Candle Light", flooringType: "Carpet", description: "Refined + effortless, the Caress Collection is styled for you. Featuring Anso® Nylon with R2X® built-in stain & soil protection, LifeGuard® Spill-Proof Backing™ and a 20-year warranty, Caress offers the best in style and design.", productSpecs: ["Flooring Type", "Carpet", "Fiber", "100% ANSO® NYLON", "Backing", "Lifeguard Blue", "Country of Origin", "US"], imageURLs: ["subtleaura-crop", "subtleaura1", "subtleaura2"], ahap: "Texture", collision: "CollisionLarge"),
    .init(id: 1, name: "Vintage Revival", colorName: "Tumeric", flooringType: "Carpet", description: "Warm up rooms and reduce energy bills with the natural insulation and comfort of carpet. With many styles to choose from and the best stain-fighting technology in the industry, Shaw carpet brings color, texture and value to your floors. Create distinctively stylish looks when you play with texture, loop, pattern and twist options.", productSpecs: ["Flooring Type", "Carpet", "Fiber", "100% Anso Soft BCF Nylon", "Backing", "Softbac Platinum", "Country of Origin", "US"], imageURLs: ["vintagerevival-crop", "vintage1", "vintage2"], ahap: "Texture", collision: "CollisionLarge"),
    .init(id: 2, name: "Inspired Design", colorName: "Ocean Villa", flooringType: "Carpet", description: "Warm up rooms and reduce energy bills with the natural insulation and comfort of carpet. With many styles to choose from and the best stain-fighting technology in the industry, Shaw carpet brings color, texture and value to your floors. Create distinctively stylish looks when you play with texture, loop, pattern and twist options.", productSpecs: ["Flooring Type", "Carpet", "Fiber", "100% Anso Soft BCF Nylon", "Backing", "Softbac Platinum", "Country of Origin", "US"], imageURLs: ["lavish-crop", "inspired1", "inspired2"], ahap: "Texture", collision: "CollisionLarge"),
    .init(id: 3, name: "Calm Serenity", colorName: "Washed Linen", flooringType: "Carpet", description: "Part of the Bellera collection, this style features high performance fiber with R2X® built-in stain & soil protection and LifeGuard® Spill-Proof Backing™. Plus, it's all covered by our No Surprises, Worry-Free™ Warranty.", productSpecs: ["Flooring Type", "Carpet", "Fiber", "100% Anso Soft BCF Nylon", "Backing", "Softbac Platinum", "Country of Origin", "US"], imageURLs: ["calmserenity-crop", "calm1", "calm2"], ahap: "Texture", collision: "CollisionLarge"),
]

let HARDWOOD_FLOORING: [Flooring] = [
    .init(id: 0, name: "Expressions", colorName: "Prose", flooringType: "Wood", description: "Warm up rooms and reduce energy bills with the natural insulation and comfort of carpet. With many styles to choose from and the best stain-fighting technology in the industry, Shaw carpet brings color, texture and value to your floors. Create distinctively stylish looks when you play with texture, loop, pattern and twist options.", productSpecs: ["Flooring Type", "Carpet", "Fiber", "100% Anso Soft BCF Nylon", "Backing", "Softbac Platinum", "Country of Origin", "US"], imageURLs: ["expressions-crop"], ahap: "Texture-solid", collision: "CollisionSmall"),
    .init(id: 1, name: "Landmark Walnut", colorName: "Washington", flooringType: "Wood", description: "Warm up rooms and reduce energy bills with the natural insulation and comfort of carpet. With many styles to choose from and the best stain-fighting technology in the industry, Shaw carpet brings color, texture and value to your floors. Create distinctively stylish looks when you play with texture, loop, pattern and twist options.", productSpecs: ["Flooring Type", "Carpet", "Fiber", "100% Anso Soft BCF Nylon", "Backing", "Softbac Platinum", "Country of Origin", "US"], imageURLs: ["landmarkwalnut-crop"], ahap: "Texture-solid", collision: "CollisionSmall"),
    .init(id: 2, name: "Empire Oak Herringbone", colorName: "Astor", flooringType: "Wood", description: "With classic charm and natural elegance, Empire Oak adds rich character to your home. This herringbone style allows you to create a unique installation that makes a stylish and bold statement on the floor.", productSpecs: ["Flooring Type", "Carpet", "Fiber", "100% Anso Soft BCF Nylon", "Backing", "Softbac Platinum", "Country of Origin", "US"], imageURLs: ["empireoak-crop"], ahap: "Texture-solid", collision: "CollisionSmall"),
]

let VINYL_FLOORING: [Flooring] = [
    .init(id: 0, name: "Paragon Mix Plus", colorName: "Brush Oak", flooringType: "Vinyl", description: "Refined + effortless, the Caress Collection is styled for you. Featuring Anso® Nylon with R2X® built-in stain & soil protection, LifeGuard® Spill-Proof Backing™ and a 20-year warranty, Caress offers the best in style and design.", productSpecs: ["Flooring Type", "Carpet", "Fiber", "100% ANSO® NYLON", "Backing", "Lifeguard Blue", "Country of Origin", "US"], imageURLs: ["paragonmixplus-crop"], ahap: "Texture-solid", collision: "CollisionSmall"),
    .init(id: 1, name: "Bascilica Plus", colorName: "Ashland Pine", flooringType: "Vinyl", description: "Refined + effortless, the Caress Collection is styled for you. Featuring Anso® Nylon with R2X® built-in stain & soil protection, LifeGuard® Spill-Proof Backing™ and a 20-year warranty, Caress offers the best in style and design.", productSpecs: ["Flooring Type", "Carpet", "Fiber", "100% ANSO® NYLON", "Backing", "Lifeguard Blue", "Country of Origin", "US"], imageURLs: ["bascilicaplus-crop"], ahap: "Texture-solid", collision: "CollisionSmall"),
    .init(id: 2, name: "Market Square", colorName: "Burlington", flooringType: "Vinyl", description: "Elegant aged look of reclaimed wood in a current color pallete of 10 various beautiful wood species.", productSpecs: ["Flooring Type", "Carpet", "Fiber", "100% ANSO® NYLON", "Backing", "Lifeguard Blue", "Country of Origin", "US"], imageURLs: ["marketsquare-crop"], ahap: "Texture-solid", collision: "CollisionSmall"),
]

let TILE_FLOORING: [Flooring] = [
    .init(id: 0, name: "Revival Maria", colorName: "Opal", flooringType: "Tile", description: "Our stunning tile & stone collections allow you to unleash your creativity with endless combinations. Designed to mimic the natural textures, like quarried slate, travertine and limestone, these looks embody flooring sophistication. Shaw tile & stone is available in ceramic, porcelain and stone and includes eco-friendly options to meet your various project needs.", productSpecs: ["Flooring Type", "Hardwood", "Species", "Red Oak", "Plank Width", "3.25", "Edge Profile", "Micro Bevel", "Surface Texture", "Smooth"],  imageURLs: ["revivalmaria-crop"], ahap: "Texture-solid", collision: "CollisionSmall"),
    .init(id: 1, name: "Islander 3x6 Wall", colorName: "Salt Water", flooringType: "Tile", description: "Our stunning tile & stone collections allow you to unleash your creativity with endless combinations. Designed to mimic the natural textures, like quarried slate, travertine and limestone, these looks embody flooring sophistication. Shaw tile & stone is available in ceramic, porcelain and stone and includes eco-friendly options to meet your various project needs.", productSpecs: ["Flooring Type", "Hardwood", "Species", "Red Oak", "Plank Width", "3.25", "Edge Profile", "Micro Bevel", "Surface Texture", "Smooth"],  imageURLs: ["islander-crop"], ahap: "Texture-solid", collision: "CollisionSmall"),
    .init(id: 2, name: "Grand Strands Wall", colorName: "Indigo", flooringType: "Tile", description: "Our stunning tile & stone collections allow you to unleash your creativity with endless combinations. Designed to mimic the natural textures, like quarried slate, travertine and limestone, these looks embody flooring sophistication. Shaw tile & stone is available in ceramic, porcelain and stone and includes eco-friendly options to meet your various project needs.", productSpecs: ["Flooring Type", "Hardwood", "Species", "Red Oak", "Plank Width", "3.25", "Edge Profile", "Micro Bevel", "Surface Texture", "Smooth"],  imageURLs: ["grandstrands-crop"], ahap: "Texture-solid", collision: "CollisionSmall"),
]
